### ISSUE TITLE
HGEALL returns empty data

### ISSUE THREAD

**Issue by scottwalker87** [camarojs/redis#1]
Here is this case
```js
async add(value) {
    try {
      const id = String(Date.now())

      await client.HSET("stat", id, value)
    } catch (error) {
      console.error(error)
    }
  },

async getAll() {
    try {
      return await client.HGETALL("stat")
    } catch (error) {
      console.error(error)
    }
  }
```
getAll() returns empty data `{}`

I have executed HGETALL via console client and there is data in there

**Comment by pikadun** [comment]
Could you provide environmental information, such as the redis version and redis protocol version you are using ?

I can't reproduce your issue, but I got another bugs: https://github.com/camarojs/redis/issues/2.

**Comment by scottwalker87** [comment]
Hello, @pikadun. Version of redis `v6.0.10` on `Alpine Linux v3.12` and version of node `v14.15.4` on `Alpine Linux v3.13`. This is docker containers

**Comment by pikadun** [comment]
When you use the default protocol version 3, HGETALL will return a map. You can use map.entries() to get data.

**Comment by scottwalker87** [comment]
Oh, yeah) The problem was with my wrapper, which used `JSON.stringify()`. Thanks and good luck!
