### ISSUE TITLE
Throws error if cannot connect to the server

### ISSUE THREAD

**Issue by andrei-markeev** [camarojs/redis#15]
## Environment

+ Node version: v14.16.0
+ Redis Server version: 6.0.3
+ Redis protocol version: v2
+ Camaro Redis version: resp2

## Describe the bug

Library doesn't listen to "error" event. When where's no error listener, Nodejs will throw exception, which will cause application to terminate. Redis is often used just for caching, so it definitely shouldn't cause application to go down.

## To Reproduce

```ts
const { ClientV2: Client } = require('@camaro/redis')
const client = new Client({
    host: "not-a-redis.com" // any non-existent host
});
```

**Comment by pikadun** [comment]
I just published [@camaro/redis (2.2.0) ](https://www.npmjs.com/package/@camaro/redis)
