### ISSUE TITLE
set chinese error

### ISSUE THREAD

**Issue by c2hy** [camarojs/redis#17]
## Environment

+ Node version:  v14.15.4
+ Redis Server version: 6.0.10
+ Redis protocol version: V3
+ Camaro Redis version: 2.1.0

## Describe the bug

when set chinese value，redis reply error: ERR Protocol error: unbalanced quotes in request. I found the value is truncated, like this: {"momentId":"013b1804-27f9-4190-9ffb-c2db9772627f","content":"尝试插入中文的内容","createdTi

## To Reproduce

Code to reproduce the behavior:

``` js
const { redisClient } = require("../src/infrastructure")
const { DateTime } = require("luxon");
const { v4: uuid } = require('uuid');

async function test() {
    const momentId = uuid();
    const createdTime = DateTime.now().toMillis();
    await redisClient.SET(`moment:${momentId}`, JSON.stringify({ momentId, content:"尝试插入中文的内容", createdTime }))
}

test()
```

**Additional context**
redis run in windows10 WSL2 docker

**Comment by pikadun** [comment]
I just published [@camaro/redis (2.2.1)](https://www.npmjs.com/package/@camaro/redis) and fix it.
