### ISSUE TITLE
add connected event callback

### ISSUE THREAD

**Issue by Dale71** [camarojs/redis#18]
## Environment

+ Node version: v15.2.1
+ Redis Server version: 6.0.3
+ Redis protocol version: 3
+ Camaro Redis version: 2.2.2

## Describe the bug

The constructor is not asynchronous and the client has no connect listener resulting in an unauthenticated error when connecting and calling a redis command

## To Reproduce

```javascript
import { ClientV3 } from '@camaro/redis';
  
(async () => {

    const client = new ClientV3({password: 'password'});

    console.log(await client.set('test', 1));
})();
```

**produces error:**
`RedisError [Redis Reply Error]: NOAUTH Authentication required.`

**Additional context**
Can you please pass back the 'on connect' event handler to the client:

```javascript
on(event, listener) {
        switch (event) {
            case 'message':
                this.parser.on(event, listener);
                break;
            case 'connect': {
                this.socket.on('connect', () => {
                    listener(event);
                });
                break;
            }
        }
    }
```

With this added in baseClient.js allows us to wait for the connection to complete

```javascript
import { ClientV3 } from '@camaro/redis';
  
const client = new ClientV3({password: 'password'});

client.on('connect', async () => {
    console.log(await client.set('test', 1));
});
```

Thanks

**Comment by pikadun** [comment]
Thanks for your feedback.
We should keep it simple and use it out of the box,  user does not need to listen for connection events, so I just queued and processed the command after the connection.
It seems to be working fine.
