### ISSUE TITLE
client doesn't reconnect to SSL

### ISSUE THREAD

**Issue by andrei-markeev** [camarojs/redis#21]
## Environment

+ Node version: v14.16.0
+ Redis Server version: 6.0.14
+ Redis protocol version: 2
+ Camaro Redis version: 2.4.0

## Describe the bug

Client doesn't reconnect to SSL.

## To Reproduce

To reproduce, you need a server with SSL, with normal TCP connections disabled.

For example, I am using Azure Redis Cache with the following configuration:

![image](https://user-images.githubusercontent.com/5181724/136294677-b549cb93-3295-47e6-9044-383dc21beabe.png)

Steps to reproduce:

1. Connect to the server via @camaro/redis client (you can use any code, just be sure to use SSL port & pass `tls: {}` parameter in the options)
2. Either reboot the Redis server or temporarily disable network connection on the computer where the test script is running
3. Wait to see if client will reconnect

When I do these steps, I receive the following error:
```
Redis error Error: read ECONNRESET
     at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
   errno: -104,
   code: 'ECONNRESET',
   syscall: 'read'
}
```

I think, this happens because reconnect function uses `this.socket.connect` in order to reconnect rather than `tls.connect`: https://github.com/camarojs/redis/blob/main/src/client/baseClient.ts#L97

**Comment by pikadun** [comment]
Thanks.
