### ISSUE TITLE
Not receiving messages from subscribed channels on protocal v2

### ISSUE THREAD

**Issue by Blockzilla101** [camarojs/redis#3]
## Environment

+ Node version: 15.4.0
+ Redis Server version: 5.0.7
+ Redis protocol version: 2
+ Camaro Redis version: 1.2.0

## Describe the bug
When using protocol v2, I dont get any messages from subscribed channels.

## To Reproduce
``` js
const client = new redis.Client({ protover: 2 });
await client.SUBSCRIBE('test');
client.on('message', data => {
    console.log(data);
})
```

**Additional context**
None

**Comment by pikadun** [comment]
I just fixed and released a new version.

**Comment by Blockzilla101** [comment]
> BTW, you should remove await before `client.SUBSCRIBE('test')`

just curious, whats the reason for that?

**Comment by pikadun** [comment]
> > BTW, you should remove await before `client.SUBSCRIBE('test')`
> 
> just curious, whats the reason for that?

This will cause some existing messages to be lost , because the existing message will be returned before registering the message event.
