### ISSUE TITLE
 ERR only (P)SUBSCRIBE / (P)...T allowed in this context even when using two clients

### ISSUE THREAD

**Issue by Blockzilla101** [camarojs/redis#4]
## Environment

+ Node version: `15.4.0`
+ Redis Server version: `5.0.7`
+ Redis protocol version: `2`
+ Camaro Redis version: `1.2.0`

## Describe the bug
Redis throwing error `ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context` even when using two seperate clients.

## To Reproduce
``` js
let publisher = new redis.Client({ protover: 2})
let subscriber = new redis.Client({ protover: 2})

subscriber.SUBSCRIBE('test')
subscriber.on('message', data => {
    console.log(data)
})

publisher.PUBLISH('test', 'hi')
```
it seems to work if i do 
```js
let subscriber = new redis.Client({ protover: 2})

subscriber.SUBSCRIBE('test')
subscriber.on('message', data => {
    console.log(data)
})

let publisher = new redis.Client({ protover: 2})
publisher.PUBLISH('test', 'hi')
```
but breaks if I try to subscribe to a new channel
```js
let subscriber = new redis.Client({ protover: 2})

subscriber.SUBSCRIBE('test')
subscriber.on('message', data => {
    console.log(data)
})

let publisher = new redis.Client({ protover: 2})
publisher.PUBLISH('test', 'hi')

subscriber.SUBSCRIBE('test2')
publisher.PUBLISH('test2', 'hi')
```

**Additional context**
None

**Comment by pikadun** [comment]
> let publisher = new redis.Client({ protover: 2})
> let subscriber = new redis.Client({ protover: 2})
> 
> subscriber.SUBSCRIBE('test')
> subscriber.on('message', data => {
>     console.log(data)
> })
> 
> publisher.PUBLISH('test', 'hi')
It seems that all commands are executed on the subscriber.
This is part of the log:
```log
127.0.0.1:6379> client list
id=28 addr=127.0.0.1:39048 fd=8 name= age=89 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=32742 obl=0 oll=0 omem=0 events=r cmd=client
id=33 addr=127.0.0.1:39072 fd=9 name= age=2 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=NULL
id=34 addr=127.0.0.1:39074 fd=10 name= age=2 idle=2 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=publish
```

**Comment by Blockzilla101** [comment]
It should use the client on which the command was invoked on tho?

**Comment by Blockzilla101** [comment]
after some message around with the package
the command is assigned to class's prototype instead of instantiated one
so when you create a new client
all command methods point to that of the new client
~~if that made any sense, hope this helps~~

**Comment by pikadun** [comment]
@Blockzilla101 Yes, the problem lies here

**Comment by Blockzilla101** [comment]
i changed it to in the generated js 
`this[command] = this[command.toUpperCase()] = fn;`
from `this.prototype[command] = this.prototype[command.toUpperCase()] = fn;`
which seems to have fixed it
no idea how to that on the ts side

**Comment by pikadun** [comment]
@Blockzilla101 I will fix it in a while ,thank you very much.

**Comment by Blockzilla101** [comment]
> @Blockzilla101 I will fix it in a while ,thank you very much.

should have seen that earlier
